M48
; DRILL file KiCad 10.0.6 date 2026-09-28T22:11:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T22:11:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X67.25Y-70.0
T2
X54.0Y-54.0
X54.0Y-151.0
X216.0Y-54.0
X216.0Y-151.0
M30
